"use client";

import { useCallback, useEffect, useRef, useState } from "react";

const ROWS=14,COLS=7;
const RANKS=["一","二","三","四","五","六","七","八","九"];
type Gravity="none"|"right"|"left"|"down"|"up"|"vertical"|"horizontal";
const GRAVITIES:Gravity[]=["none","right","left","down","up","vertical","horizontal"];
const RULES=["牌阵固定","消除后向右补位","消除后向左补位","消除后向下补位","消除后向上补位","向上、向下分流","向左、向右分流"];
const TITLES=["初入雀门","顺水推舟","逆风行舟","落花听雨","青云直上","两仪分流","四海归一","竹影听风","三元会馆","九莲宝灯"];
const LEVELS=Array.from({length:200},(_,i)=>({name:`${TITLES[i%TITLES.length]} · ${i+1}`,icons:Math.min(12+Math.floor(i/8),27),gravity:GRAVITIES[i%GRAVITIES.length],rule:`${RULES[i%RULES.length]} · ${12+Math.floor(i/20)}阶牌阵`,reward:20+Math.floor(i/10)*5}));
const PACKS=[{price:6,gems:60,tag:"入门"},{price:30,gems:330,tag:"加赠10%"},{price:68,gems:780,tag:"热门"},{price:128,gems:1580,tag:"加赠23%"},{price:328,gems:4480,tag:"超值"},{price:648,gems:9800,tag:"豪华"}];
type Cell=number|null; type Pos=[number,number];
const idx=(r:number,c:number)=>r*COLS+c;
function shuffle<T>(v:T[]){const a=[...v];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function newBoard(n:number):Cell[]{const a:number[]=[];for(let i=0;i<ROWS*COLS/2;i++){const v=i%n;a.push(v,v)}return shuffle(a)}
function tileName(v:number){return`${RANKS[v%9]}${v<9?"万":v<18?"筒":"条"}`}
function TileFace({value}:{value:number}){const rank=value%9+1;if(value<9)return <span className="wan-face"><b>{RANKS[rank-1]}</b><i>萬</i></span>;if(value<18)return <span className={`dot-face dots-${rank}`}>{Array.from({length:rank},(_,i)=><i key={i}/>)}</span>;return <span className={`bamboo-face bamboo-${rank}`}>{Array.from({length:rank},(_,i)=><i key={i}><b/></i>)}</span>}

function findPath(board:Cell[],a:Pos,b:Pos):Pos[]|null{
 if(a[0]===b[0]&&a[1]===b[1]||board[idx(...a)]==null||board[idx(...a)]!==board[idx(...b)])return null;
 const h=ROWS+2,w=COLS+2,dirs:Pos[]=[[1,0],[-1,0],[0,1],[0,-1]];
 const open=(r:number,c:number)=>r===0||c===0||r===h-1||c===w-1||board[idx(r-1,c-1)]==null||(r-1===b[0]&&c-1===b[1]);
 const s:Pos=[a[0]+1,a[1]+1],t:Pos=[b[0]+1,b[1]+1]; type Node={r:number;c:number;d:number;turns:number;path:Pos[]};
 const q:Node[]=dirs.map((_,d)=>({r:s[0],c:s[1],d,turns:0,path:[s]})),seen=new Map<string,number>();
 while(q.length){const cur=q.shift()!;for(let nd=0;nd<4;nd++){const turns=cur.turns+(nd===cur.d?0:1);if(turns>2)continue;const nr=cur.r+dirs[nd][0],nc=cur.c+dirs[nd][1];if(nr<0||nc<0||nr>=h||nc>=w||!open(nr,nc))continue;const key=`${nr},${nc},${nd}`;if((seen.get(key)??9)<=turns)continue;seen.set(key,turns);const path=nd===cur.d?cur.path:[...cur.path,[cur.r,cur.c]as Pos];if(nr===t[0]&&nc===t[1])return[...path,t].map(([r,c])=>[r-1,c-1]);q.push({r:nr,c:nc,d:nd,turns,path})}}
 return null;
}
function availableMove(board:Cell[]):[Pos,Pos]|null{const g=new Map<number,Pos[]>();board.forEach((v,i)=>{if(v!=null)g.set(v,[...(g.get(v)||[]),[Math.floor(i/COLS),i%COLS]])});for(const a of g.values())for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(findPath(board,a[i],a[j]))return[a[i],a[j]];return null}
function applyGravity(board:Cell[],gravity:Gravity):Cell[]{if(gravity==="none")return board;const out:Array<Cell>=Array(ROWS*COLS).fill(null);const putRow=(r:number,cells:Cell[],start:number)=>cells.forEach((v,i)=>out[idx(r,start+i)]=v);const putCol=(c:number,cells:Cell[],start:number)=>cells.forEach((v,i)=>out[idx(start+i,c)]=v);
 if(gravity==="left"||gravity==="right"){for(let r=0;r<ROWS;r++){const a=board.slice(r*COLS,(r+1)*COLS).filter(v=>v!=null);putRow(r,a,gravity==="left"?0:COLS-a.length)}}
 if(gravity==="up"||gravity==="down"){for(let c=0;c<COLS;c++){const a=Array.from({length:ROWS},(_,r)=>board[idx(r,c)]).filter(v=>v!=null);putCol(c,a,gravity==="up"?0:ROWS-a.length)}}
 if(gravity==="vertical"){const mid=Math.ceil(ROWS/2);for(let c=0;c<COLS;c++){const top=Array.from({length:mid},(_,r)=>board[idx(r,c)]).filter(v=>v!=null),bottom=Array.from({length:ROWS-mid},(_,r)=>board[idx(r+mid,c)]).filter(v=>v!=null);putCol(c,top,0);putCol(c,bottom,ROWS-bottom.length)}}
 if(gravity==="horizontal"){const mid=Math.ceil(COLS/2);for(let r=0;r<ROWS;r++){const row=board.slice(r*COLS,(r+1)*COLS),left=row.slice(0,mid).filter(v=>v!=null),right=row.slice(mid).filter(v=>v!=null);putRow(r,left,0);putRow(r,right,COLS-right.length)}}return out}

export default function Home(){
 const[level,setLevel]=useState(0),[board,setBoard]=useState<Cell[]>(()=>newBoard(LEVELS[0].icons)),[selected,setSelected]=useState<Pos|null>(null),[linkPath,setLinkPath]=useState<Pos[]>([]),[score,setScore]=useState(0),[combo,setCombo]=useState(0),[time,setTime]=useState(0),[timerStarted,setTimerStarted]=useState(false),[notice,setNotice]=useState("点击任意麻将开始本关计时"),[hint,setHint]=useState<Pos[]>([]),[won,setWon]=useState(false),[gems,setGems]=useState(80),[spent,setSpent]=useState(0),[shop,setShop]=useState(false),[clearMode,setClearMode]=useState(false),[earned,setEarned]=useState(false),[maxUnlocked,setMaxUnlocked]=useState(0),[levelMap,setLevelMap]=useState(false);const busy=useRef(false);
 useEffect(()=>{const saved=localStorage.getItem("mahjong-wallet");if(saved)try{const x=JSON.parse(saved);setGems(x.gems??80);setSpent(x.spent??0);setMaxUnlocked(Math.min(x.maxUnlocked??0,199))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("mahjong-wallet",JSON.stringify({gems,spent,maxUnlocked}))},[gems,spent,maxUnlocked]);
 const startLevel=useCallback((n:number)=>{if(n>maxUnlocked)return;setLevel(n);setBoard(newBoard(LEVELS[n].icons));setSelected(null);setLinkPath([]);setHint([]);setTime(0);setTimerStarted(false);setCombo(0);setWon(false);setEarned(false);setClearMode(false);setLevelMap(false);setNotice("点击任意麻将开始本关计时")},[maxUnlocked]);
 const reshuffle=useCallback((automatic=false)=>{setBoard(prev=>{const pos=prev.map((v,i)=>v==null?-1:i).filter(i=>i>=0);let vals=shuffle(pos.map(i=>prev[i]as number)),next=[...prev];pos.forEach((p,i)=>next[p]=vals[i]);for(let k=0;k<30&&!availableMove(next);k++){vals=shuffle(vals);next=[...prev];pos.forEach((p,i)=>next[p]=vals[i])}return next});setSelected(null);setHint([]);setNotice(automatic?"牌局无解，已自动刷新":"已使用刷新道具")},[]);
 useEffect(()=>{const t=setInterval(()=>setTime(v=>won||!timerStarted?v:v+1),1000);return()=>clearInterval(t)},[won,timerStarted]);
 const finishCheck=(next:Cell[])=>setTimeout(()=>{busy.current=false;if(next.every(v=>v==null)){setWon(true);setScore(s=>s+Math.max(100,1000-time));if(!earned){setGems(g=>g+LEVELS[level].reward);setMaxUnlocked(u=>Math.max(u,Math.min(level+1,199)));setEarned(true)}setNotice(level===LEVELS.length-1?"恭喜完成全部200关！":"本关完成，下一关已激活！")}else if(!availableMove(next))reshuffle(true)},220);
 const buy=(cost:number,action:()=>void)=>{if(gems<cost){setNotice("钻石不足，选择礼包补充钻石");setShop(true);return}setGems(g=>g-cost);action()};
 const choose=(r:number,c:number)=>{if(busy.current||won||board[idx(r,c)]==null)return;if(!timerStarted){setTimerStarted(true);setNotice("计时开始，祝你一气呵成！")}setHint([]);if(clearMode){const kind=board[idx(r,c)],next=board.map(v=>v===kind?null:v);setClearMode(false);setBoard(applyGravity(next,LEVELS[level].gravity));setScore(s=>s+next.filter(v=>v===null).length*10);setNotice(`已消除全部${tileName(kind!)}牌`);finishCheck(applyGravity(next,LEVELS[level].gravity));return}if(!selected){setSelected([r,c]);return}if(selected[0]===r&&selected[1]===c){setSelected(null);return}const path=findPath(board,selected,[r,c]);if(!path){setCombo(0);setNotice(board[idx(...selected)]===board[idx(r,c)]?"这两张牌无法连通":"请选择相同的牌");setSelected([r,c]);return}busy.current=true;const first=selected;setLinkPath(path);setNotice("连线成功！");setTimeout(()=>{let next=[...board];next[idx(...first)]=null;next[idx(r,c)]=null;next=applyGravity(next,LEVELS[level].gravity);const n=combo+1;setCombo(n);setScore(s=>s+100+Math.min(n,10)*10);setBoard(next);setSelected(null);setLinkPath([]);setNotice(n>=3?`${n} 连击 · ${LEVELS[level].rule}`:LEVELS[level].rule);finishCheck(next)},500)};
 const useHint=()=>buy(15,()=>{const m=availableMove(board);if(m){setHint(m);setNotice("已标出一对可消除的牌")}}),useRefresh=()=>buy(30,()=>reshuffle(false)),useClear=()=>buy(60,()=>{setClearMode(true);setSelected(null);setNotice("请点击想要全部消除的花色")});
 const recharge=(p:typeof PACKS[number])=>{setGems(g=>g+p.gems);setSpent(s=>s+p.price);setNotice(`模拟充值成功，获得 ${p.gems} 钻石`);setShop(false)};
 const remaining=board.filter(v=>v!=null).length;
 const visibleLevels=Array.from({length:Math.min(5,LEVELS.length)},(_,k)=>Math.max(0,Math.min(level-2,LEVELS.length-5))+k);
 return <main><header className="topbar"><div className="brand"><span className="seal">雀</span><div><h1>雀影连连</h1><p>MAHJONG LINK</p></div></div><div className="level-track">{visibleLevels.map(i=><button key={i} disabled={i>maxUnlocked} className={i===level?"active":i<maxUnlocked?"done":i>maxUnlocked?"locked":""} onClick={()=>startLevel(i)}><b>{i>maxUnlocked?"🔒":i+1}</b><span>{i===level?LEVELS[i].name:`第${i+1}关`}</span></button>)}<button className="map-button" onClick={()=>setLevelMap(true)}><b>☰</b><span>全部关卡</span></button></div><button className="wallet" onClick={()=>setShop(true)}><span>◆</span><b>{gems}</b><small>充值</small></button></header>
 <section className="game-shell"><aside className="panel info-panel"><div className="stage-title"><small>第 {level+1} 关</small><h2>{LEVELS[level].name}</h2><em>{LEVELS[level].rule}</em><p>完成本关奖励 <b>◆ {LEVELS[level].reward}</b></p></div><div className="stat"><span>得分</span><strong>{score.toLocaleString()}</strong></div><div className="stat"><span>剩余牌数</span><strong>{remaining}<small> / 98</small></strong></div><div className="stat"><span>连击</span><strong className="red">× {combo}</strong></div><div className="rule"><b>本关补位</b><p>每次消除后，麻将牌将按“{LEVELS[level].rule}”移动。无可连牌时自动刷新。</p></div></aside>
 <div className={`board-wrap ${clearMode?"clear-mode":""}`}><div className="timer"><span>第 {level+1} / 200 关 · {LEVELS[level].rule}</span><strong className={timerStarted?"running":"waiting"}><small>{timerStarted?"计时中":"点击开局"}</small> {String(Math.floor(time/60)).padStart(2,"0")}:{String(time%60).padStart(2,"0")}</strong><div className="level-progress"><i style={{width:`${(level+1)/200*100}%`}}/></div></div><div className="board" role="grid">{board.map((tile,i)=>{const r=Math.floor(i/COLS),c=i%COLS,active=selected?.[0]===r&&selected?.[1]===c,hinted=hint.some(p=>p[0]===r&&p[1]===c);return <button key={i} aria-label={tile==null?"已消除":tileName(tile)} className={`tile tile-${tile??0} ${tile==null?"empty":""} ${active?"selected":""} ${hinted?"hinted":""}`} onClick={()=>choose(r,c)}>{tile==null?"":<TileFace value={tile}/>}</button>})}{linkPath.length>0&&<svg className="link-line" viewBox={`0 0 ${COLS} ${ROWS}`} preserveAspectRatio="none" aria-hidden="true"><polyline points={linkPath.map(([r,c])=>`${Math.max(.08,Math.min(COLS-.08,c+.5))},${Math.max(.08,Math.min(ROWS-.08,r+.5))}`).join(" ")}/></svg>}</div><div className="message"><span>◆</span>{notice}<span>◆</span></div></div>
 <aside className="panel action-panel"><h3>锦囊道具</h3><button onClick={useHint}><span>灯</span><b>提示</b><small>◆ 15 · 标出一对</small></button><button onClick={useClear}><span>清</span><b>指定花色</b><small>◆ 60 · 全部消除</small></button><button onClick={useRefresh}><span>洗</span><b>刷新</b><small>◆ 30 · 重排牌局</small></button><div className="auto"><i/>无解时免费自动刷新</div></aside></section>
 {won&&<div className="modal-backdrop"><div className="modal"><span className="seal big">雀</span><h2>{remaining===0?notice:"本局结束"}</h2><p>{remaining===0?`通关奖励 ◆ ${LEVELS[level].reward} 已到账`:`距离胜利还剩 ${remaining} 张牌`}</p><button onClick={()=>remaining===0&&level<LEVELS.length-1?startLevel(level+1):startLevel(level)}>{remaining===0&&level<LEVELS.length-1?"进入下一关":"再来一局"}</button></div></div>}
 {shop&&<div className="modal-backdrop"><div className="shop-modal"><button className="close" onClick={()=>setShop(false)}>×</button><div className="shop-head"><span className="seal">钻</span><div><small>模拟充值中心</small><h2>补充钻石</h2></div></div><div className="balance"><span>当前钻石 <b>◆ {gems}</b></span><span>累计充值 <b>¥ {spent.toFixed(2)}</b></span></div><p className="disclaimer">体验模式 · 点击礼包不会产生真实扣款，仅记录模拟充值金额</p><div className="packs">{PACKS.map(p=><button key={p.price} onClick={()=>recharge(p)}><em>{p.tag}</em><strong>◆ {p.gems}</strong><span>¥ {p.price}</span></button>)}</div></div></div>}
 {levelMap&&<div className="modal-backdrop"><div className="level-modal"><button className="close" onClick={()=>setLevelMap(false)}>×</button><h2>雀门二百关</h2><p>已激活 {maxUnlocked+1} / 200 · 完成当前关才能激活下一关</p><div className="level-grid">{LEVELS.map((l,i)=><button key={i} disabled={i>maxUnlocked} className={i===level?"current":i<maxUnlocked?"passed":""} onClick={()=>startLevel(i)}><b>{i>maxUnlocked?"🔒":i+1}</b><small>{i>maxUnlocked?"未激活":i===level?"进行中":i<maxUnlocked?"已完成":"待挑战"}</small></button>)}</div></div></div>}
 <footer>© 雀影连连 · 一局清风，一味闲趣</footer></main>
}
